FROM alpine:latest

RUN apk add --no-cache \
    bash \
    openldap-clients \
    netcat-openbsd \
    curl

# add test ad objects to the ad-server 
COPY seed.sh /usr/local/bin/seed-run.sh
RUN chmod +x /usr/local/bin/seed-run.sh

CMD ["/bin/bash", "/usr/local/bin/seed-run.sh"]